### ISSUE TITLE
Blog URL with trailing slash leads to error page

### ISSUE THREAD

**Issue by jamesmosier** [kentcdodds/old-kentcdodds.com#94] opened 2019-03-12 15:38 UTC
When navigating to `https://kentcdodds.com/blog/` (note trailing slash) an error is thrown by the browser telling the user that `This site can’t be reached`. If you remove the trailing slash, you are directed to the blog as expected.

This was brought to my attention via Google by clicking on the link in the screenshot:

![Screen Shot 2019-03-12 at 11 35 08 AM](https://user-images.githubusercontent.com/2854919/54213671-27ded980-44bb-11e9-9b74-390fdb933434.png)

Once at the blog it is great 🎉  Thanks for the awesome content Kent!

**Comment by kentcdodds** [comment] 2019-03-12 21:23
Hi @jamesmosier!

Thanks for the report. I'm unable to reproduce this issue however. I'm not sure what to do about it 😬  So I'll go ahead and close this. If you can find someone else who can reproduce it as well then we'll know it's probably not just something wrong with your browser and we can look into it. Thanks!

**Closed as completed by kentcdodds** 2019-03-12 21:23 UTC
